apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: go-api-template
  namespace: myapp
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: go-api-template
