apiVersion: v1
kind: Secret
metadata:
  name: go-api-template-secrets
  namespace: myapp
type: Opaque
stringData:
  DB_HOST: "CHANGE_ME"
  DB_PORT: "5432"
  DB_USER: "CHANGE_ME"
  DB_PASSWORD: "CHANGE_ME"
  DB_NAME: "CHANGE_ME"
  REDIS_URL: "CHANGE_ME"
  JWT_SECRET: "CHANGE_ME"
  KAFKA_BROKERS: "CHANGE_ME"
