apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: go-api-template
  namespace: myapp
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: go-api-template
  endpoints:
    - port: metrics
      interval: 15s
      path: /metrics
  namespaceSelector:
    matchNames:
      - myapp
