// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: users.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
WHERE deleted_at IS NULL
  AND (
    CASE WHEN $1::text = '' THEN true
         ELSE full_name ILIKE '%' || $1 || '%'
              OR email ILIKE '%' || $1 || '%'
              OR username ILIKE '%' || $1 || '%'
    END
  )
  AND (CASE WHEN $2::text = '' THEN true ELSE role = $2 END)
`

type CountUsersParams struct {
	Search string `json:"search"`
	Role   string `json:"role"`
}

// Count users matching the same filters as ListUsers.
func (q *Queries) CountUsers(ctx context.Context, arg CountUsersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers, arg.Search, arg.Role)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, email, full_name, password_hash, role)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, username, email, full_name, password_hash, role, is_active, metadata, created_at, updated_at, deleted_at
`

type CreateUserParams struct {
	Username     string      `json:"username"`
	Email        string      `json:"email"`
	FullName     string      `json:"full_name"`
	PasswordHash pgtype.Text `json:"password_hash"`
	Role         string      `json:"role"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (*User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.Email,
		arg.FullName,
		arg.PasswordHash,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.FullName,
		&i.PasswordHash,
		&i.Role,
		&i.IsActive,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, email, full_name, password_hash, role, is_active, metadata, created_at, updated_at, deleted_at FROM users
WHERE email = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (*User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.FullName,
		&i.PasswordHash,
		&i.Role,
		&i.IsActive,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, email, full_name, password_hash, role, is_active, metadata, created_at, updated_at, deleted_at FROM users
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (*User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.FullName,
		&i.PasswordHash,
		&i.Role,
		&i.IsActive,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, email, full_name, password_hash, role, is_active, metadata, created_at, updated_at, deleted_at FROM users
WHERE username = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (*User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.FullName,
		&i.PasswordHash,
		&i.Role,
		&i.IsActive,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, email, full_name, password_hash, role, is_active, metadata, created_at, updated_at, deleted_at FROM users
WHERE deleted_at IS NULL
  AND (
    CASE WHEN $1::text = '' THEN true
         ELSE full_name ILIKE '%' || $1 || '%'
              OR email ILIKE '%' || $1 || '%'
              OR username ILIKE '%' || $1 || '%'
    END
  )
  AND (CASE WHEN $2::text = '' THEN true ELSE role = $2 END)
ORDER BY created_at DESC
LIMIT $4::int OFFSET $3::int
`

type ListUsersParams struct {
	Search     string `json:"search"`
	Role       string `json:"role"`
	PageOffset int32  `json:"page_offset"`
	PageSize   int32  `json:"page_size"`
}

// List users with optional search and role filter, paginated.
func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]*User, error) {
	rows, err := q.db.Query(ctx, listUsers,
		arg.Search,
		arg.Role,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.FullName,
			&i.PasswordHash,
			&i.Role,
			&i.IsActive,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteUser = `-- name: SoftDeleteUser :exec
UPDATE users
SET deleted_at = NOW(), updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteUser, id)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
  full_name  = COALESCE($1, full_name),
  role       = COALESCE($2, role),
  is_active  = COALESCE($3, is_active),
  updated_at = NOW()
WHERE id = $4 AND deleted_at IS NULL
RETURNING id, username, email, full_name, password_hash, role, is_active, metadata, created_at, updated_at, deleted_at
`

type UpdateUserParams struct {
	FullName string    `json:"full_name"`
	Role     string    `json:"role"`
	IsActive bool      `json:"is_active"`
	ID       uuid.UUID `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (*User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.FullName,
		arg.Role,
		arg.IsActive,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.FullName,
		&i.PasswordHash,
		&i.Role,
		&i.IsActive,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}
