#!/usr/bin/env bash
###############################################################################
# init.sh — Interactive project setup
#
# Asks which stacks to enable, generates .env with only needed config.
#
# Usage:
#   ./scripts/init.sh
#   ./scripts/init.sh --all        # enable everything
#   ./scripts/init.sh --minimal    # DB + Redis only
###############################################################################

set -euo pipefail

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m'

info()  { echo -e "${GREEN}[✓]${NC} $1"; }
warn()  { echo -e "${YELLOW}[!]${NC} $1"; }
header() { echo -e "\n${BOLD}${CYAN}$1${NC}"; }

# Defaults
PROJECT_NAME="myapp"
DB_DRIVER="gorm"
ENABLE_REDIS=true
ENABLE_KAFKA=false
ENABLE_ELASTICSEARCH=false
ENABLE_FIREBASE=false
ENABLE_SENDGRID=false
ENABLE_STRIPE=false
ENABLE_ICEWARP=false
ENABLE_SONAR=false
ENABLE_OTEL=false
ENABLE_ENCRYPTION=false

# ---------------------------------------------------------------------------
# Parse flags
# ---------------------------------------------------------------------------
if [[ "${1:-}" == "--all" ]]; then
    ENABLE_REDIS=true; ENABLE_KAFKA=true; ENABLE_ELASTICSEARCH=true
    ENABLE_FIREBASE=true; ENABLE_SENDGRID=true; ENABLE_STRIPE=true
    ENABLE_ICEWARP=true; ENABLE_SONAR=true; ENABLE_OTEL=true
    ENABLE_ENCRYPTION=true
elif [[ "${1:-}" == "--minimal" ]]; then
    ENABLE_REDIS=true
    # everything else stays false
elif [[ "${1:-}" != "" ]]; then
    echo "Usage: ./scripts/init.sh [--all|--minimal]"
    echo "  (no flag) = interactive mode"
    exit 0
else
    # ---------------------------------------------------------------------------
    # Interactive mode
    # ---------------------------------------------------------------------------
    echo ""
    echo -e "${BOLD}╔══════════════════════════════════════════════╗${NC}"
    echo -e "${BOLD}║      Go API Template — Project Setup        ║${NC}"
    echo -e "${BOLD}╚══════════════════════════════════════════════╝${NC}"

    ask() {
        local var=$1 prompt=$2 default=$3
        echo -ne "  ${prompt} [${default}]: "
        read -r input
        eval "$var=\"${input:-$default}\""
    }

    ask_yn() {
        local var=$1 prompt=$2 default=$3
        echo -ne "  ${prompt} (y/n) [${default}]: "
        read -r input
        input="${input:-$default}"
        if [[ "$input" == "y" || "$input" == "Y" ]]; then
            eval "$var=true"
        else
            eval "$var=false"
        fi
    }

    header "1. Project"
    ask PROJECT_NAME "Project name" "$PROJECT_NAME"

    header "2. Database"
    echo "  Drivers: sqlc (raw SQL), gorm (ORM), mongo (MongoDB)"
    ask DB_DRIVER "Database driver" "$DB_DRIVER"

    header "3. Infrastructure"
    ask_yn ENABLE_REDIS        "Enable Redis (cache, pub/sub)?" "y"
    ask_yn ENABLE_KAFKA        "Enable Kafka (message broker)?" "n"
    ask_yn ENABLE_ELASTICSEARCH "Enable Elasticsearch (search)?" "n"
    ask_yn ENABLE_OTEL         "Enable OpenTelemetry tracing?" "n"
    ask_yn ENABLE_ENCRYPTION   "Enable field-level encryption (AES-256)?" "n"

    header "4. External Services"
    ask_yn ENABLE_SENDGRID "Enable SendGrid (email)?" "n"
    ask_yn ENABLE_STRIPE   "Enable Stripe (payments)?" "n"
    ask_yn ENABLE_ICEWARP  "Enable IceWarp (mail server)?" "n"
    ask_yn ENABLE_FIREBASE "Enable Firebase (push notifications)?" "n"

    header "5. Code Quality"
    ask_yn ENABLE_SONAR "Enable SonarQube (code analysis)?" "n"
fi

# ---------------------------------------------------------------------------
# Generate .env
# ---------------------------------------------------------------------------
header "Generating .env..."

cat > .env << ENVEOF
# Generated by scripts/init.sh — $(date)
# Project: ${PROJECT_NAME}

# Server
SERVER_PORT=8080
SERVER_MODE=debug

# Database
DB_DRIVER=${DB_DRIVER}
DB_HOST=localhost
DB_PORT=5432
DB_USER=postgres
DB_PASSWORD=postgres
DB_NAME=${PROJECT_NAME}
DB_SSL_MODE=disable
DB_MAX_CONNS=10
DB_MIN_CONNS=2
DB_CONN_MAX_LIFETIME=1h
DB_CONN_MAX_IDLE_TIME=30m
ENVEOF

if [[ "$DB_DRIVER" == "mongo" ]]; then
    cat >> .env << 'ENVEOF'

# MongoDB
MONGO_URI=mongodb://localhost:27017
MONGO_DB_NAME=${PROJECT_NAME}
ENVEOF
fi

if [[ "$ENABLE_REDIS" == "true" ]]; then
    cat >> .env << 'ENVEOF'

# Redis
REDIS_URL=redis://localhost:6379/0
REDIS_POOL_SIZE=10
REDIS_MIN_IDLE=2
ENVEOF
fi

cat >> .env << 'ENVEOF'

# Auth
AUTH_PROVIDER=jwt
JWT_SECRET=CHANGE-ME-$(openssl rand -hex 16)
JWT_EXPIRY=24h
ENVEOF

if [[ "$ENABLE_ENCRYPTION" == "true" ]]; then
    KEY=$(openssl rand -hex 32)
    cat >> .env << ENVEOF

# Encryption (AES-256-GCM)
ENCRYPTION_KEY=${KEY}
ENVEOF
fi

if [[ "$ENABLE_SENDGRID" == "true" ]]; then
    cat >> .env << 'ENVEOF'

# SendGrid
SENDGRID_URL=https://api.sendgrid.com
SENDGRID_API_KEY=
SENDGRID_FROM=noreply@example.com
ENVEOF
fi

if [[ "$ENABLE_STRIPE" == "true" ]]; then
    cat >> .env << 'ENVEOF'

# Stripe
STRIPE_URL=https://api.stripe.com
STRIPE_SECRET_KEY=
ENVEOF
fi

if [[ "$ENABLE_ICEWARP" == "true" ]]; then
    cat >> .env << 'ENVEOF'

# IceWarp
ICEWARP_URL=
ICEWARP_USERNAME=
ICEWARP_PASSWORD=
ICEWARP_FROM=
ENVEOF
fi

if [[ "$ENABLE_FIREBASE" == "true" ]]; then
    cat >> .env << 'ENVEOF'

# Firebase
FIREBASE_CREDENTIALS_FILE=
FIREBASE_PROJECT_ID=
ENVEOF
fi

if [[ "$ENABLE_ELASTICSEARCH" == "true" ]]; then
    cat >> .env << 'ENVEOF'

# Elasticsearch
ELASTIC_URLS=http://localhost:9200
ELASTIC_USERNAME=
ELASTIC_PASSWORD=
ENVEOF
fi

if [[ "$ENABLE_KAFKA" == "true" ]]; then
    cat >> .env << ENVEOF

# Kafka
KAFKA_BROKERS=localhost:9092
KAFKA_CONSUMER_GROUP=${PROJECT_NAME}-group
ENVEOF
fi

if [[ "$ENABLE_OTEL" == "true" ]]; then
    cat >> .env << ENVEOF

# OpenTelemetry
OTEL_ENABLED=true
OTEL_SERVICE_NAME=${PROJECT_NAME}
OTEL_ENDPOINT=localhost:4318
ENVEOF
fi

cat >> .env << 'ENVEOF'

# Workers
WORKER_COUNT=4
WORKER_QUEUE_SIZE=100

# Logging
LOG_LEVEL=debug
LOG_FORMAT=console
ENVEOF

info ".env generated"

# ---------------------------------------------------------------------------
# Generate docker-compose.override.yml with selected services
# ---------------------------------------------------------------------------
header "Generating docker-compose.override.yml..."

cat > docker-compose.override.yml << 'COMPEOF'
# Generated by scripts/init.sh — only enabled services
services:
COMPEOF

if [[ "$ENABLE_KAFKA" == "true" ]]; then
    cat >> docker-compose.override.yml << 'COMPEOF'
  kafka:
    image: bitnami/kafka:3.7
    restart: unless-stopped
    ports:
      - "9092:9092"
    environment:
      KAFKA_CFG_NODE_ID: 0
      KAFKA_CFG_PROCESS_ROLES: controller,broker
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 0@kafka:9093
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
    volumes:
      - kafka_data:/bitnami/kafka

COMPEOF
fi

if [[ "$ENABLE_ELASTICSEARCH" == "true" ]]; then
    cat >> docker-compose.override.yml << 'COMPEOF'
  elasticsearch:
    image: elasticsearch:8.13.0
    restart: unless-stopped
    ports:
      - "9200:9200"
    environment:
      discovery.type: single-node
      xpack.security.enabled: "false"
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    volumes:
      - es_data:/usr/share/elasticsearch/data

COMPEOF
fi

if [[ "$ENABLE_SONAR" == "true" ]]; then
    cat >> docker-compose.override.yml << 'COMPEOF'
  sonarqube:
    image: sonarqube:10-community
    restart: unless-stopped
    ports:
      - "9000:9000"
    environment:
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: "true"
    volumes:
      - sonar_data:/opt/sonarqube/data

COMPEOF
fi

# Add volumes
VOLUMES=""
[[ "$ENABLE_KAFKA" == "true" ]] && VOLUMES="${VOLUMES}  kafka_data:\n"
[[ "$ENABLE_ELASTICSEARCH" == "true" ]] && VOLUMES="${VOLUMES}  es_data:\n"
[[ "$ENABLE_SONAR" == "true" ]] && VOLUMES="${VOLUMES}  sonar_data:\n"

if [[ -n "$VOLUMES" ]]; then
    echo "" >> docker-compose.override.yml
    echo "volumes:" >> docker-compose.override.yml
    echo -e "$VOLUMES" >> docker-compose.override.yml
fi

info "docker-compose.override.yml generated"

# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------
echo ""
echo -e "${BOLD}═══════════════════════════════════════════════════${NC}"
echo -e "${BOLD} Setup Complete!${NC}"
echo -e "${BOLD}═══════════════════════════════════════════════════${NC}"
echo ""
echo "  Project:     ${PROJECT_NAME}"
echo "  DB Driver:   ${DB_DRIVER}"
echo ""
echo "  Enabled stacks:"
[[ "$ENABLE_REDIS" == "true" ]]         && echo "    ✓ Redis"
[[ "$ENABLE_KAFKA" == "true" ]]         && echo "    ✓ Kafka"
[[ "$ENABLE_ELASTICSEARCH" == "true" ]] && echo "    ✓ Elasticsearch"
[[ "$ENABLE_OTEL" == "true" ]]          && echo "    ✓ OpenTelemetry"
[[ "$ENABLE_ENCRYPTION" == "true" ]]    && echo "    ✓ Encryption (AES-256)"
[[ "$ENABLE_SENDGRID" == "true" ]]      && echo "    ✓ SendGrid"
[[ "$ENABLE_STRIPE" == "true" ]]        && echo "    ✓ Stripe"
[[ "$ENABLE_ICEWARP" == "true" ]]       && echo "    ✓ IceWarp"
[[ "$ENABLE_FIREBASE" == "true" ]]      && echo "    ✓ Firebase"
[[ "$ENABLE_SONAR" == "true" ]]         && echo "    ✓ SonarQube"
echo ""
echo "  Next steps:"
echo "    1. docker compose up -d"
echo "    2. make build"
echo "    3. ./bin/${PROJECT_NAME} serve"
[[ "$ENABLE_SONAR" == "true" ]] && echo "    4. ./scripts/setup-sonar.sh"
echo ""
